apiVersion: v1
kind: ConfigMap
metadata:
  name: spiffe-helper-config
  namespace: demo
data:
  helper.conf: |
    agent_address = "/spiffe-workload-api/spire-agent.sock"
    cmd = "/bin/sh"
    cmd_args = "create-secret.sh"
    svid_file_name = "svid.pem"
    svid_key_file_name = "svid_key.pem"
    svid_bundle_file_name = "svid_bundle.pem"